### ISSUE TITLE
Watchdog timeout

### ISSUE THREAD

**Issue by Romz24** [Szum123321/textile_backup#42] opened 2020-10-28 10:16 UTC
When using your mod, the server crashes.

Mod version: **2.0.1-1.16.3**

[crash-2020-10-28_13.11.58-server.txt](https://github.com/Szum123321/textile_backup/files/5451102/crash-2020-10-28_13.11.58-server.txt)

**Comment by Szum123321** [comment] 2020-10-28 10:19
Yes, that's defently the reason fo crash. Could you also provide config file?

**Comment by Romz24** [comment] 2020-10-28 10:28
yes

[textile_backup.json5.txt](https://github.com/Szum123321/textile_backup/files/5451164/textile_backup.json5.txt)
_(I added .txt to the end of the file, otherwise it didn't want to upload to the site.)_

**Comment by Romz24** [comment] 2020-10-28 10:31
I want to add that the problem appeared after updating the fabric api and loader, it seemed there were no problems before.

Fabric Loader: **0.10.5+build.213**
Fabric API: **0.24.3+build.414-1.16**

**Comment by Szum123321** [comment] 2020-11-10 09:28
I'm not sure what causes this issue but it's possible that some sort of multihread problem occurs when both minecraft server and backup mod try to access world files.

Here's a compiled version with changes from 42_bugfix branch, that should stop server from changing save files while the backup is being made.
[textile_backup-2.0.2-1.16.3.zip](https://github.com/Szum123321/textile_backup/files/5516180/textile_backup-2.0.2-1.16.3.zip)

Could you confirm it works?

**Comment by Szum123321** [comment] 2020-11-25 09:30
Ok, I'm guessing everything is alright.
Closing issue.

**Comment by j0r1s** [comment] 2020-12-06 12:34
I'm still having a crash on backup with version 2.0.2 / 2.0.1 of the mod :

[crash-2020-12-06_12.27.20-server.txt](https://github.com/Szum123321/textile_backup/files/5648738/crash-2020-12-06_12.27.20-server.txt)

```bash
 java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)
```

Minecraft version : 1.16.4

**Comment by Szum123321** [comment] 2020-12-06 14:21
Can you tell me what additional mods are you using and where do you run your server (some hosting website)?

**Comment by j0r1s** [comment] 2020-12-06 14:34
I've tried again and it seems to be working now.
I might have been running a chunk pre-generation mod during my first backup attempts that would explain why they would fail.

I'll still post additional mods :
```sh
ls mods
carpet-autocraftingtable-1.16.4-1.4.17_build2.jar
fabric-carpet-1.16.4-1.4.18+v201121.jar
lithium-fabric-mc1.16.4-0.6.0.jar
textile_backup-2.0.2-1.16.3.jar
carpet-extra-1.16.4-1.4.16.jar
fabric-chunkpregen-0.3.3.jar
malilib-fabric-1.16.4-0.10.0-dev.21+arne.2.jar
Xaeros_Minimap_20.27.3_Fabric_1.16.4.jar
fabric-api-0.26.2+1.16.jar
 litematica-fabric-1.16.4-0.0.0-dev.20201103.184101.jar
phosphor-fabric-mc1.16.1-0.6.0+build.7.jar
```

I'm hosting the server on my own private server running on debian10 with those kind of specs : 

- Intel  Xeon E3-1245v2 -  4c / 8t ( 3,4GHz )
- 32GB DDR3 1333MHz
- SoftRaid  3x2To   SATA

I'll keep you in touch but for now issue seems to be resolved, thanks for your quick reaction anyway !

**Comment by Szum123321** [comment] 2020-12-06 14:46
That makes sense. Thank you for this piece of information. I'll soon try to confirm it.

**Comment by Setadokalo** [comment] 2021-03-07 11:01
I believe this bug is triggered by trying to backup a very large world, which takes long enough to cause the server thread to crash itself (believing that it's frozen). This appears to be confirmed in the first answer for https://bugs.mojang.com/browse/MC-149200 .

**Comment by Szum123321** [comment] 2021-06-19 17:12
Repaired in realese 2.1.0

**Closed as completed by Szum123321** 2021-06-19 17:12 UTC
Labels: bug
